
# Pull base image
FROM debian

# Install dependencies
RUN apt-get update
RUN apt-get install -y \
    python3 \
    python3-dev \
    python3-pip \
    python3-virtualenv \
    python3-flask \
    python3-requests \
    zip \
    imagemagick \
    --allow-unauthenticated \
    --no-install-recommends

COPY ./ /data/
COPY policy.xml  /etc/ImageMagick-6/policy.xml

# Define working directory
 WORKDIR /data

# Define default command
CMD ["python3", "flask_prog.py"]
